### ISSUE TITLE
Define yaml configuration input file

### ISSUE THREAD

**Issue by williamfgc** [ORNL/RIOPA.jl#9]
The input configuration file is the main point of interaction from the user's perspective to define.

[ ]  Define overall file structure and account for our target use case AMReX-Castro

Allow for data payload variations across processors using percentages:
[ ]  Payload range
[ ]  Payload statistical distribution 

Allow for time variability evolution: polynomial, exponential?
[ ]  Functional form using math (if possible in Julia)
[ ]  Expression form

**Comment by williamfgc** [comment]
Draft:

```yaml
- dataset: output
  name: "Checkpoint restart"
  nsteps: 10
  base_name: "checkpoint-restart"
  compute_seconds: 0.001 # optional
  transport: "HDF5" # optional
  
  data_streams:
    - name: "Level0"
      evolution: quadratic, a, b, c
      # evolution: "ax^2+bx+c" (candidate if possible)
      nprocs_ratio:  0.5  # optional 
      procs_payloads:
         - size_range: [5,10]
            ratio:  0.06
         - size_range: [10,20]
            ratio: 0.94
           
    - name: "Level1" 
      proc_payloads:
         - size_range: [5,10]
           percentage:  6
         - size_range: [10,20]
           percentage: 94
```

**Comment by PhilipFackler** [comment]
@williamfgc, here we have both `ratio` and `percentage` used. Did we want to support both?

**Comment by williamfgc** [comment]
My choice would be `ratio` for now to not increase maintenance of too many things at once. Also, percentage without the `%` doesn't look complete. We can also use fractions with `ratio=1/4`. Thoughts?

**Comment by PhilipFackler** [comment]
We can use [getfield](https://docs.julialang.org/en/v1/base/base/#Core.getfield) with a distribution name from [Distributions](https://juliastats.org/Distributions.jl/stable/univariate/#Index) (with user-provided parameters) to instantiate a given distribution within which to generate random numbers for process payload sizes.

https://stackoverflow.com/questions/34016768/julia-invoke-a-function-by-a-given-string

**Comment by williamfgc** [comment]
Agree on the dangers, let's restrict what users can do. I'd just look for  the character `/` and get the numerator and denominator.

**Comment by PhilipFackler** [comment]
```julia
function Base.parse(::Type{Rational{Int}}, x::AbstractString)
    ms, ns = split(x, '/', keepempty=false)
    m = parse(Int, ms)
    n = parse(Int, ns)
    return m//n
end

Base.parse(::Type{Rational}, x::AbstractString) = parse(Rational{Int}, x)
```

Do a `tryparse(Float64, x)` and then use this implementation to parse as rational (and convert to float).

**Comment by PhilipFackler** [comment]
See [here](https://stackoverflow.com/questions/59543961/how-to-read-a-polynomial-from-a-text-file-in-julia) to try out parsing polynomial expressions. Using the example verbatim would require the "PEG" and "TypedPolynomials" packages.

**Comment by williamfgc** [comment]
@PhilipFackler sounds good, let's try and see what it looks like on the user-facing yaml file. We can always do other types of expressions e.g. `exp`.

**Comment by PhilipFackler** [comment]
See #26.
This could be specified all in one line:
```yaml
      evolution: Polynomial, <a_0>, <a_1>, ...

      evolution: GrowthFactor, <a>
```
or with multiple keywords:
```yaml
      evolution:
        function: Polynomial
        parameters: [ <a_0>, <a_1>, ... ]

      evolution:
        function: GrowthFactor
        parameters: [ <a> ]
```
